services:
  server:
    image: nginx:stable
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/.
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8.3-fpm
    container_name: php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html/.
